project_id = "wjaulyvqzywcnkegnzoh"

[functions.fetch-google-reviews]
verify_jwt = false

[functions.submit-review]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.check-blog-schedule]
verify_jwt = false

[functions.check-spelling]
verify_jwt = false

[functions.ping-blog-post]
verify_jwt = false

[functions.convert-image]
verify_jwt = false
